"""initial

Revision ID: b121cbe7ab0a
Revises:
Create Date: 2025-12-27 14:33:26.500297

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b121cbe7ab0a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("logger_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_entries_id"), "log_entries", ["id"], unique=False)
    op.create_table(
        "service_configurations",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("config_key", sa.String(), nullable=True),
        sa.Column("config_value", sa.String(), nullable=True),
        sa.Column("config_type", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("config_id"),
    )
    op.create_table(
        "user_conversation_threads",
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("thread_id"),
    )
    op.create_table(
        "user_conversations",
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("response_to", sa.Integer(), nullable=True),
        sa.Column("last_operator", sa.String(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_rate", sa.Integer(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "user_invites",
        sa.Column("invite_code", sa.String(), nullable=False),
        sa.Column("count_left", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expire_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("invite_code"),
    )
    op.create_table(
        "user_tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("create_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_heartbeat_timestamp", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("heartbeat_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("task_stage", sa.Integer(), nullable=True),
        sa.Column("persistent_context", sa.String(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hashed", sa.String(), nullable=True),
        sa.Column("create_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("multi_session_ok", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("register_ip_hashed", sa.String(), nullable=True),
        sa.Column("last_login_ip_hashed", sa.String(), nullable=True),
        sa.Column("last_login_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_session", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("invite_code", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("user_tasks")
    op.drop_table("user_invites")
    op.drop_table("user_conversations")
    op.drop_table("user_conversation_threads")
    op.drop_table("service_configurations")
    op.drop_index(op.f("ix_log_entries_id"), table_name="log_entries")
    op.drop_table("log_entries")
    # ### end Alembic commands ###
